# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '16', '17', '19', '21' ]
        runs-on: [ubuntu-latest, macos-12, windows-latest, macos-latest]
        exclude:
          - runs-on: macos-latest
            java: "8"
          - runs-on: macos-latest
            java: "16"

    name: Test on Java ${{ matrix.Java }} on ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.Java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.Java }}
        distribution: 'adopt'

    - name: Build with Ant
      run: ant jar

    - name: Run some examples & test with ant (non Win)
      if: ${{ matrix.runs-on != 'windows-latest' }}
      uses: coactions/setup-xvfb@v1
      with:
          run: |
            ./run.sh examples/l22_small.swc -exportnml1
            ./run.sh examples/l22_small.swc -exportnml2

            # Test with 
            ant testnogui

    - name: Run some examples & test with ant (Windows)
      if: ${{ matrix.runs-on == 'windows-latest' }}
      run: |
            ./run.sh examples/l22_small.swc -exportnml1
            ./run.sh examples/l22_small.swc -exportnml2

            # Test with 
            ant testnogui

